//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateWebSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURPOS()
        {
            this.REAL_ESTATES = new HashSet<REAL_ESTATES>();
        }
    
        public int ID { get; set; }
        public string PURPOSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REAL_ESTATES> REAL_ESTATES { get; set; }
    }
}
