//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateWebSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class REAL_ESTATES
    {
        public int ID { get; set; }
        public string CITY { get; set; }
        public string AREA { get; set; }
        public int CATEGORY_ID { get; set; }
        public int PURPOSE_ID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual PURPOS PURPOS { get; set; }
    }
}
